import {
  LayoutDashboard,
  Building2,
  CalendarCheck,
  LogOut as MoveOutIcon,
  UserCheck,
  Activity,
  Receipt,
  ShieldCheck,
  FileCheck2,
  BarChart3,
  Bell,
  CreditCard,
  Share2,
  ScrollText,
  Settings,
} from 'lucide-react';
import { ROLES } from '../constants/roles';

export const superAdminNavigation = [
  {
    id: 'admin-dashboard',
    label: 'Dashboard',
    path: '/admin/dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-tenants',
    label: 'Tenants & Hostels',
    path: '/admin/tenants',
    icon: Building2,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-properties',
    label: 'Properties & Units',
    path: '/admin/properties',
    icon: Building2,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-bookings',
    label: 'Platform Bookings',
    path: '/admin/bookings',
    icon: CalendarCheck,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-move-outs',
    label: 'Move-Outs',
    path: '/admin/move-outs',
    icon: MoveOutIcon,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-residents',
    label: 'All Residents',
    path: '/admin/residents',
    icon: UserCheck,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-operations',
    label: 'Operations & Staff',
    path: '/admin/operations',
    icon: Activity,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-finance',
    label: 'Payments & Finance',
    path: '/admin/finance',
    icon: Receipt,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-approvals',
    label: 'KYC & Approvals',
    path: '/admin/approvals',
    icon: ShieldCheck,
    badge: '3',
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-compliance',
    label: 'Compliance',
    path: '/admin/compliance',
    icon: FileCheck2,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-reports',
    label: 'Analytics & Reports',
    path: '/admin/reports',
    icon: BarChart3,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-notifications',
    label: 'Notifications',
    path: '/admin/notifications',
    icon: Bell,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-subscriptions',
    label: 'Subscriptions & Billing',
    path: '/admin/subscriptions',
    icon: CreditCard,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-referrals',
    label: 'Referrals & Affiliates',
    path: '/admin/referrals',
    icon: Share2,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-audit-logs',
    label: 'System Audit Logs',
    path: '/admin/audit-logs',
    icon: ScrollText,
    roles: [ROLES.SUPER_ADMIN],
  },
  {
    id: 'admin-settings',
    label: 'Platform Settings',
    path: '/admin/settings',
    icon: Settings,
    roles: [ROLES.SUPER_ADMIN],
  },
];
