import {
  LayoutDashboard,
  Building2,
  BedDouble,
  CalendarCheck,
  Users,
  Receipt,
  MessageSquareWarning,
  Wrench,
  UserCog,
  Boxes,
  UtensilsCrossed,
  Settings,
} from 'lucide-react';
import { ROLES } from '../constants/roles';

export const tenantNavigation = [
  {
    id: 'tenant-dashboard',
    label: 'Dashboard',
    path: '/tenant/dashboard',
    icon: LayoutDashboard,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-properties',
    label: 'My Properties',
    path: '/tenant/properties',
    icon: Building2,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-rooms',
    label: 'Rooms & Beds',
    path: '/tenant/rooms',
    icon: BedDouble,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-bookings',
    label: 'Bookings & Admissions',
    path: '/tenant/bookings',
    icon: CalendarCheck,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-residents',
    label: 'Residents Directory',
    path: '/tenant/residents',
    icon: Users,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-payments',
    label: 'Rent & Payments',
    path: '/tenant/payments',
    icon: Receipt,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-complaints',
    label: 'Complaints & Helpdesk',
    path: '/tenant/complaints',
    icon: MessageSquareWarning,
    badge: '2',
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-maintenance',
    label: 'Maintenance & Tasks',
    path: '/tenant/maintenance',
    icon: Wrench,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-staff',
    label: 'Hostel Staff',
    path: '/tenant/staff',
    icon: UserCog,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-inventory',
    label: 'Assets & Inventory',
    path: '/tenant/inventory',
    icon: Boxes,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-food-menu',
    label: 'Mess & Food Menu',
    path: '/tenant/food-menu',
    icon: UtensilsCrossed,
    roles: [ROLES.TENANT],
  },
  {
    id: 'tenant-settings',
    label: 'Hostel Settings',
    path: '/tenant/settings',
    icon: Settings,
    roles: [ROLES.TENANT],
  },
];
